### ISSUE TITLE
Build failure on Fedora 40 with cairo 1.18.0

### ISSUE THREAD

**Issue by ycollet** [rerdavies/ToobAmp#48]
I am trying to build toobamp on Fedora 40 with cairo 1.18.0 and I meet the following error:
```
[ 39%] Building CXX object src/CMakeFiles/ToobAmp.dir/LsNumerics/BinaryReader.cpp.o
cd /home/collette/rpmbuild/BUILD/ToobAmp/redhat-linux-build/src && /usr/bin/g++ -DNAM_SAMPLE_FLOAT -DRTNEURAL_DEFAULT_ALIGNMENT=16 -DRTNEURAL_USE_XSIMD=1 -DToobAmp_EXPORTS -I/home/collette/rpmbuild/BUILD/ToobAmp/src/../modules/RTNeural -I/home/collette/rpmbuild/BUILD/ToobAmp/src/../modules/NeuralAmpModelerCore/Dependencies/eigen -I/home/collette/rpmbuild/BUILD/ToobAmp/src/../modules/NeuralAmpModelerCore/Dependencies/nlohmann -I/home/collette/rpmbuild/BUILD/ToobAmp/src/../modules/NeuralAmpModelerCore -I/home/collette/rpmbuild/BUILD/ToobAmp/src/../modules -I/home/collette/rpmbuild/BUILD/ToobAmp/modules/RTNeural/RTNeural/../modules/json -I/home/collette/rpmbuild/BUILD/ToobAmp/modules/RTNeural/modules/xsimd/include -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  -include algorithm -include cstdint -Wno-psabi  -Wall -pedantic -Wno-reorder -Wno-restrict  -std=gnu++20 -fPIC -MD -MT src/CMakeFiles/ToobAmp.dir/LsNumerics/BinaryReader.cpp.o -MF CMakeFiles/ToobAmp.dir/LsNumerics/BinaryReader.cpp.o.d -o CMakeFiles/ToobAmp.dir/LsNumerics/BinaryReader.cpp.o -c /home/collette/rpmbuild/BUILD/ToobAmp/src/LsNumerics/BinaryReader.cpp
/home/collette/rpmbuild/BUILD/ToobAmp/modules/lv2cairo/src/lv2c/Lv2cDropShadowElement.cpp: In member function ‘void lv2c::Lv2cDropShadowElement::DrawDropShadow(lv2c::Lv2cDrawingContext&, const lv2c::Lv2cRectangle&)’:
/home/collette/rpmbuild/BUILD/ToobAmp/modules/lv2cairo/src/lv2c/Lv2cDropShadowElement.cpp:496:35: error: ‘renderSurface’ has both ‘extern’ and initializer
  496 |     cairo_public cairo_surface_t *renderSurface = cairo_image_surface_create(
      |                                   ^~~~~~~~~~~~~
/home/collette/rpmbuild/BUILD/ToobAmp/modules/lv2cairo/src/lv2c/Lv2cDropShadowElement.cpp:502:10: error: ‘renderSurface’ was not declared in this scope; did you mean ‘renderSurfaceX’?
  502 |         [renderSurface]()
      |          ^~~~~~~~~~~~~
      |          renderSurfaceX
/home/collette/rpmbuild/BUILD/ToobAmp/modules/lv2cairo/src/lv2c/Lv2cDropShadowElement.cpp: In lambda function:
/home/collette/rpmbuild/BUILD/ToobAmp/modules/lv2cairo/src/lv2c/Lv2cDropShadowElement.cpp:504:35: error: ‘renderSurface’ is not captured
  504 |             cairo_surface_destroy(renderSurface);
      |                                   ^~~~~~~~~~~~~
/home/collette/rpmbuild/BUILD/ToobAmp/modules/lv2cairo/src/lv2c/Lv2cDropShadowElement.cpp:502:23: note: the lambda has no capture-default
  502 |         [renderSurface]()
      |                       ^
/home/collette/rpmbuild/BUILD/ToobAmp/modules/lv2cairo/src/lv2c/Lv2cDropShadowElement.cpp:502:10: note: ‘<typeprefixerror>renderSurface’ declared here
  502 |         [renderSurface]()
      |          ^~~~~~~~~~~~~

```

**Comment by rerdavies** [comment]
A fix is in one of the project's submodules to the project (LV2Cairo).

cd to your project directory, and run the following command:

      git submodule update --init --recursive
      git pull origin master

I think that will address the compile issue. Whether it works on Fedora 40 or not.... ? 

Keep me updated.

**Comment by rerdavies** [comment]
Please ignore the previous message.

Do this instead:

       git pull origin master
       git submodule update  modules/lv2cairo

**Comment by ycollet** [comment]
Thanks for your answer. I will test this tomorrow.

**Comment by ycollet** [comment]
I tested and I was able to build the plugins.
I needed to fix one or 2 things like a missing header in modules/lv2cairo and using dynamic libraries for ogg and some other libs, but other than that, the build went fine.

**Comment by rerdavies** [comment]
Hmm. Be careful with that one. There's a nasty versioning/compatibility issue involved with the ogg file dynamic libraries (which is why I did my best to link them statically).  I can't remember the exact issue. But I generally remember it as this: the FLAC C++ wrappers HAVE to be linked statically (they are tightly versioned, and are not portable across debian versions); and that library has highly version-dependent linkages in to libogg. And libogg (only) is not avaiable as a static libogg.a file on older versions of debian. If you had to link the dynamic library to make it work, that's all good; but be aware that you probably don't want to be making it available for other distros.  (A bitter lesson how not to build linux binaries for me personally).

If you would like to (and if the fixes are pretty isolated) feel free to push or send me whatever changes you made, and I'll do my best to merge with the current sources.  I imagine the include header changes are portable. And I can probably work out SOME way to decide if the libogg.a library is available in  CMakeList.txt files. Make a pull request with your unmodified changes, and we/I can work out how best to merge with mainline sources. Or just zip everyting up and send it to me, if you're not set up to deal with a github push, and I'll do what I can to push your changes into mainline.
